version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "master" # The branch to create pull requests against.
    schedule:
      interval: "monthly"
    commit-message:
      # Prefix all commit messages with "[github-actions] "
      prefix: "[github-actions] "

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "master" # The branch to create pull requests against.
    versioning-strategy: increase
    groups:
      "NPM Dependencies":
        update-types:
          - "major"
          - "minor"
          - "patch"
    schedule:
      interval: "monthly"
    commit-message:
      # Prefix all commit messages with "[npm] "
      prefix: "[npm] "

  # Maintain dependencies for Composer
  - package-ecosystem: "composer"
    directory: "/"
    target-branch: "master" # The branch to create pull requests against.
    versioning-strategy: increase
    groups:
      "Composer Dependencies":
        update-types:
          - "major"
          - "minor"
          - "patch"
    schedule:
      interval: "monthly"
    # Ignore specific dependencies
    ignore:
      # Pin `brianhenryie/strauss` to a specific max version
      - dependency-name: "brianhenryie/strauss"
        versions: [">0.21.1"]
    commit-message:
      # Prefix all commit messages with "[composer] "
      prefix: "[composer] "
